### PR TITLE
Add CF-Community repository for installing the plugin

### PR DESCRIPTION
**Pull request by mattmcneeney**
Add `-r CF-Community` to the `cf install-plugin` command in the readme

### CODE REVIEW

**Comment by sclevine** [comment]
Thanks for the contribution @mattmcneeney!

It hasn't been necessary to specify the plugin repo since cf CLI [v6.27.0](https://github.com/cloudfoundry/cli/releases/tag/v6.27.0). Were you aware of that, or do you have another motivation for suggesting that we explicitly specify the repo in the README?

**Comment by mattmcneeney** [comment]
@sclevine I wasn't aware of that 😄  I just checked and I'm still on version `6.25.0+787326d95.2017-02-28` which explains why I ran into difficulty.

Since this is fixed in the latest CLI version you can probably just close this PR if you want to. I was just worried that folks just getting started on CF wouldn't know how to resolve this if this was happening on the latest version!

**Comment by sclevine** [comment]
If you'd like to modify the PR to add an extra section to the README.md for CLI versions < v6.27.0, I would definitely merge it. Otherwise I'll wait to see if other users run into the same issue, and make the change then.

**Comment by mattmcneeney** [comment]
@sclevine How's this? Feel free to hold off on merging or close this for now if you want to wait to see if others report this issue!

**Comment by sclevine** [comment]
Can you change the wording to `Furthermore, if...`, so it's clear that the "outdated" part refers to the plugin version, not the CLI version?

(I'm on a plane traveling back from EU CF Summit -- otherwise I would do this myself after the merge.)

**Comment by mattmcneeney** [comment]
@sclevine done!

**Comment by sclevine** [comment]
Sorry, one last thing: the option is `-r`, not `-R`, and it comes after the plugin name by the docs:
```
cf install-plugin PLUGIN_NAME [-r REPO_NAME] [-f]
```

**Comment by sclevine** [comment]
Or I can merge it and add a commit on top when my plane lands, either way.

**Comment by mattmcneeney** [comment]
Sure. If it’s still open on Monday I can fix it, otherwise feel free to
either merge and fix or just push a commit directly and close this!

**Comment by mattmcneeney** [comment]
@sclevine Totally forgot about this until now, but I updated the PR following your comments in case this is still useful, otherwise feel free to close!

**Comment by sclevine** [comment]
Sorry for the delay, merging now!

**Pull request merged**
